// =============================================================================
// TEGN: TypeScript Embedded NES Macro Assembler
//
// This file is autogenerated - do not edit by hand.
// Instead edit opsGenerator.ts and run "npm run generate"
// =============================================================================
export function ADC(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([105, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([101, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([101, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([117, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([117, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([109, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([125, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([125, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([121, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([121, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "prex")
        return { type: "opDescription", bytes: new Uint8Array([97, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([97, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "posty")
        return { type: "opDescription", bytes: new Uint8Array([113, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([113, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function AND(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([41, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([37, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([37, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([53, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([53, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([45, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([61, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([61, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([57, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([57, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "prex")
        return { type: "opDescription", bytes: new Uint8Array([33, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([33, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "posty")
        return { type: "opDescription", bytes: new Uint8Array([49, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([49, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function ASL(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([10]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([6, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([6, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([22, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([22, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([14, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([30, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([30, 0, 0]), symbol: a1, size: 16, isRelative: false };
    throw new Error("not Implemented");
}
export function BCC(a1, a2) {
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([144, 0]), symbol: a1, size: 8, isRelative: true };
    throw new Error("not Implemented");
}
export function BCS(a1, a2) {
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([176, 0]), symbol: a1, size: 8, isRelative: true };
    throw new Error("not Implemented");
}
export function BEQ(a1, a2) {
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([240, 0]), symbol: a1, size: 8, isRelative: true };
    throw new Error("not Implemented");
}
export function BIT(a1, a2) {
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([36, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([36, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([44, a1.value & 0xff, a1.value >> 8]) };
    throw new Error("not Implemented");
}
export function BMI(a1, a2) {
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([48, 0]), symbol: a1, size: 8, isRelative: true };
    throw new Error("not Implemented");
}
export function BNE(a1, a2) {
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([208, 0]), symbol: a1, size: 8, isRelative: true };
    throw new Error("not Implemented");
}
export function BPL(a1, a2) {
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([16, 0]), symbol: a1, size: 8, isRelative: true };
    throw new Error("not Implemented");
}
export function BRK(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([0]) };
    throw new Error("not Implemented");
}
export function BVC(a1, a2) {
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([80, 0]), symbol: a1, size: 8, isRelative: true };
    throw new Error("not Implemented");
}
export function BVS(a1, a2) {
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([112, 0]), symbol: a1, size: 8, isRelative: true };
    throw new Error("not Implemented");
}
export function CLC(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([24]) };
    throw new Error("not Implemented");
}
export function CLD(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([216]) };
    throw new Error("not Implemented");
}
export function CLI(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([88]) };
    throw new Error("not Implemented");
}
export function CLV(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([184]) };
    throw new Error("not Implemented");
}
export function CMP(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([201, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([197, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([197, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([213, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([213, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([205, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([221, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([221, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([217, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([217, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "prex")
        return { type: "opDescription", bytes: new Uint8Array([193, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([193, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "posty")
        return { type: "opDescription", bytes: new Uint8Array([209, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([209, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function CPX(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([224, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([228, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([228, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([236, a1.value & 0xff, a1.value >> 8]) };
    throw new Error("not Implemented");
}
export function CPY(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([192, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([196, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([196, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([204, a1.value & 0xff, a1.value >> 8]) };
    throw new Error("not Implemented");
}
export function DEC(a1, a2) {
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([198, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([198, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([214, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([214, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([206, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([222, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([222, 0, 0]), symbol: a1, size: 16, isRelative: false };
    throw new Error("not Implemented");
}
export function DEX(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([202]) };
    throw new Error("not Implemented");
}
export function DEY(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([136]) };
    throw new Error("not Implemented");
}
export function EOR(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([73, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([69, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([69, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([85, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([85, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([77, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([93, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([93, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([89, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([89, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "prex")
        return { type: "opDescription", bytes: new Uint8Array([65, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([65, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "posty")
        return { type: "opDescription", bytes: new Uint8Array([81, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([81, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function INC(a1, a2) {
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([230, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([230, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([246, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([246, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([238, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([254, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([254, 0, 0]), symbol: a1, size: 16, isRelative: false };
    throw new Error("not Implemented");
}
export function INX(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([232]) };
    throw new Error("not Implemented");
}
export function INY(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([200]) };
    throw new Error("not Implemented");
}
export function JMP(a1, a2) {
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([76, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "Indirect")
        return { type: "opDescription", bytes: new Uint8Array([108, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([108, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function JSR(a1, a2) {
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([32, a1.value & 0xff, a1.value >> 8]) };
    throw new Error("not Implemented");
}
export function LDA(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([169, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([165, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([165, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([181, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([181, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([173, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([189, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([189, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([185, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([185, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "prex")
        return { type: "opDescription", bytes: new Uint8Array([161, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([161, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "posty")
        return { type: "opDescription", bytes: new Uint8Array([177, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([177, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function LDX(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([162, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([166, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([166, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([182, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([182, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([174, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([190, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([190, 0, 0]), symbol: a1, size: 16, isRelative: false };
    throw new Error("not Implemented");
}
export function LDY(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([160, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([164, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([164, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([180, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([180, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([172, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([188, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([188, 0, 0]), symbol: a1, size: 16, isRelative: false };
    throw new Error("not Implemented");
}
export function LSR(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([74]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([70, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([70, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([86, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([86, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([78, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([94, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([94, 0, 0]), symbol: a1, size: 16, isRelative: false };
    throw new Error("not Implemented");
}
export function NOP(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([234]) };
    throw new Error("not Implemented");
}
export function ORA(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([9, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([5, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([5, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([21, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([21, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([13, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([29, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([29, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([25, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([25, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "prex")
        return { type: "opDescription", bytes: new Uint8Array([1, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([1, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "posty")
        return { type: "opDescription", bytes: new Uint8Array([17, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([17, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function PHA(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([72]) };
    throw new Error("not Implemented");
}
export function PHP(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([8]) };
    throw new Error("not Implemented");
}
export function PLA(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([104]) };
    throw new Error("not Implemented");
}
export function PLP(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([40]) };
    throw new Error("not Implemented");
}
export function ROL(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([42]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([38, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([38, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([54, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([54, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([46, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([62, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([62, 0, 0]), symbol: a1, size: 16, isRelative: false };
    throw new Error("not Implemented");
}
export function ROR(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([106]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([102, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([102, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([118, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([118, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([110, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([126, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([126, 0, 0]), symbol: a1, size: 16, isRelative: false };
    throw new Error("not Implemented");
}
export function RTI(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([64]) };
    throw new Error("not Implemented");
}
export function RTS(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([96]) };
    throw new Error("not Implemented");
}
export function SBC(a1, a2) {
    if (arguments.length === 1 && a1.type === "Immediate")
        return { type: "opDescription", bytes: new Uint8Array([233, a1.value]) };
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([229, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([229, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([245, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([245, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([237, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([253, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([253, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([249, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([249, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "prex")
        return { type: "opDescription", bytes: new Uint8Array([225, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([225, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "posty")
        return { type: "opDescription", bytes: new Uint8Array([241, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([241, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function SEC(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([56]) };
    throw new Error("not Implemented");
}
export function SED(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([248]) };
    throw new Error("not Implemented");
}
export function SEI(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([120]) };
    throw new Error("not Implemented");
}
export function STA(a1, a2) {
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([133, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([133, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([149, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([149, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([141, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([157, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([157, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Absolute" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([153, a1.value & 0xff, a1.value >> 8]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([153, 0, 0]), symbol: a1, size: 16, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "prex")
        return { type: "opDescription", bytes: new Uint8Array([129, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([129, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "Indirect" && a2 === "posty")
        return { type: "opDescription", bytes: new Uint8Array([145, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([145, 0]), symbol: a1, size: 8, isRelative: false };
    throw new Error("not Implemented");
}
export function STX(a1, a2) {
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([134, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([134, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "y")
        return { type: "opDescription", bytes: new Uint8Array([150, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([150, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([142, a1.value & 0xff, a1.value >> 8]) };
    throw new Error("not Implemented");
}
export function STY(a1, a2) {
    if (arguments.length === 1 && a1.type === "ZeroPage")
        return { type: "opDescription", bytes: new Uint8Array([132, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([132, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 2 && a1.type === "ZeroPage" && a2 === "x")
        return { type: "opDescription", bytes: new Uint8Array([148, a1.value]) };
    if (arguments.length === 1 && a1.type === "SymbolicLabel")
        return { type: "opDescription", bytes: new Uint8Array([148, 0]), symbol: a1, size: 8, isRelative: false };
    if (arguments.length === 1 && a1.type === "Absolute")
        return { type: "opDescription", bytes: new Uint8Array([140, a1.value & 0xff, a1.value >> 8]) };
    throw new Error("not Implemented");
}
export function TAX(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([170]) };
    throw new Error("not Implemented");
}
export function TAY(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([168]) };
    throw new Error("not Implemented");
}
export function TSX(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([186]) };
    throw new Error("not Implemented");
}
export function TXA(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([138]) };
    throw new Error("not Implemented");
}
export function TXS(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([154]) };
    throw new Error("not Implemented");
}
export function TYA(a1, a2) {
    if (arguments.length === 0)
        return { type: "opDescription", bytes: new Uint8Array([152]) };
    throw new Error("not Implemented");
}
//# sourceMappingURL=ops.js.map